version: '3.1'

services:

  mongo:
    image: mongo
    restart: always

  dpd:
    image: dpd
    restart: always
    ports: 
      - 2403:2403
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
