version: '3.1'

services:

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  dpd:
    image: dpd
    restart: always
    ports: 
      - 2403:2403
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
